# Generated by Django 5.0.1 on 2026-05-05 21:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_update_software_incident_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="RiskPrediction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "risk_score",
                    models.FloatField(help_text="Risk probability (0.0 to 1.0)"),
                ),
                (
                    "risk_level",
                    models.CharField(
                        choices=[
                            ("LOW", "Low Risk - Green"),
                            ("MEDIUM", "Medium Risk - Orange"),
                            ("HIGH", "High Risk - Red"),
                        ],
                        help_text="LOW (<0.4), MEDIUM (0.4-0.7), HIGH (>0.7)",
                        max_length=20,
                    ),
                ),
                (
                    "confidence",
                    models.FloatField(
                        default=0.5,
                        help_text="Model confidence in prediction (0.0 to 1.0)",
                    ),
                ),
                ("incident_count_30d", models.IntegerField(default=0)),
                ("avg_downtime_hours", models.FloatField(default=0.0)),
                ("time_since_last_incident_days", models.IntegerField(default=0)),
                ("hardware_incident_ratio", models.FloatField(default=0.5)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "equipement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="risk_predictions",
                        to="api.equipement",
                    ),
                ),
            ],
            options={
                "db_table": "risk_predictions",
                "ordering": ["-risk_score", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["equipement", "-created_at"],
                        name="risk_predic_equipem_5619cc_idx",
                    ),
                    models.Index(
                        fields=["-risk_score"], name="risk_predic_risk_sc_2adf14_idx"
                    ),
                ],
            },
        ),
    ]
