# Generated by Django 5.0.1 on 2026-05-09 20:05

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('risk_category', models.CharField(choices=[('low', 'Low Risk'), ('medium', 'Medium Risk'), ('high', 'High Risk'), ('critical', 'Critical Risk')], default='medium', max_length=20)),
                ('location', models.CharField(blank=True, default='', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ai_zones',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DetectionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_image', models.ImageField(upload_to='detections/original/')),
                ('annotated_image', models.ImageField(blank=True, null=True, upload_to='detections/annotated/')),
                ('detection_results', models.JSONField(default=dict)),
                ('processing_time_ms', models.FloatField(default=0.0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detection_events', to=settings.AUTH_USER_MODEL)),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detection_events', to='ai_engine.zone')),
            ],
            options={
                'db_table': 'ai_detection_events',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SafetyViolation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('violation_type', models.CharField(choices=[('no_helmet', 'No Helmet / Hardhat'), ('no_vest', 'No Safety Vest'), ('no_mask', 'No Face Mask'), ('no_gloves', 'No Gloves'), ('unauthorized_person', 'Unauthorized Person'), ('other', 'Other Violation')], max_length=30)),
                ('confidence_score', models.FloatField(help_text='Model confidence 0.0–1.0')),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('bounding_box', models.JSONField(default=dict)),
                ('notes', models.TextField(blank=True, default='')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('detection_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='violations', to='ai_engine.detectionevent')),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='violations', to='ai_engine.zone')),
            ],
            options={
                'db_table': 'ai_safety_violations',
                'ordering': ['-timestamp'],
            },
        ),
    ]
