# Generated by Django 5.0.1 on 2026-05-10 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_engine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detectionevent',
            name='compliance_status',
            field=models.BooleanField(default=True, help_text='True if compliant with zone rules'),
        ),
        migrations.AddField(
            model_name='detectionevent',
            name='risk_score',
            field=models.CharField(default='LOW', help_text='LOW, MEDIUM, HIGH, CRITICAL', max_length=20),
        ),
        migrations.AddField(
            model_name='safetyviolation',
            name='ai_summary',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='safetyviolation',
            name='detected_ppe',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='safetyviolation',
            name='required_ppe',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='safetyviolation',
            name='severity',
            field=models.CharField(default='medium', max_length=20),
        ),
        migrations.AddField(
            model_name='safetyviolation',
            name='zone_risk',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='zone',
            name='compliance_threshold',
            field=models.FloatField(default=80.0, help_text='Minimum compliance rate required'),
        ),
        migrations.AddField(
            model_name='zone',
            name='required_ppe_rules',
            field=models.JSONField(default=list, help_text='List of required PPE (helmet, vest, gloves, mask)'),
        ),
    ]
