# Generated by Django 5.0.1 on 2026-05-10 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_engine', '0002_detectionevent_compliance_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detectionevent',
            name='ai_summary',
            field=models.TextField(blank=True, default=''),
        ),
    ]
