# Generated by Django 5.0.1 on 2026-05-10 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_engine', '0003_detectionevent_ai_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='safetyviolation',
            name='violation_type',
            field=models.CharField(choices=[('no_helmet', 'No Helmet / Hardhat'), ('no_vest', 'No Safety Vest'), ('no_mask', 'No Face Mask'), ('no_gloves', 'No Gloves'), ('no_shoes', 'No Safety Shoes'), ('no_glasses', 'No Eye Protection'), ('unauthorized_person', 'Unauthorized Person'), ('other', 'Other Violation')], max_length=30),
        ),
    ]
